version: '3'
services:
  api:
    container_name: api-container
    restart: always
    build: ./server
    image: eloback/server
    ports:
      - "5001:3001"
  client:
    container_name: client-container
    restart: always
    build: ./client
    image: eloback/client
    ports:
      - "5000:3000"
    depends_on:
      - api
