version: '3.8'
services:
  api:
    container_name: api-container
    restart: always
    build: ./server
    ports:
      - "5001:3001"
  client:
    container_name: client-container
    restart: always
    build: ./client
    ports:
      - "5000:3000"
    depends_on:
      - api
